-- Demo data: a handful of Pokemon already synchronized locally (mirrors what US03 produces).

insert into pokemon (id, name, height, weight, sprite_url, category, description) values
  (1, 'bulbasaur', 7, 69, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 'Seed Pokémon', 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.'),
  (2, 'ivysaur', 10, 130, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 'Seed Pokémon', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.'),
  (3, 'venusaur', 20, 1000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 'Seed Pokémon', 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.'),
  (4, 'charmander', 6, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 'Lizard Pokémon', 'It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.'),
  (5, 'charmeleon', 11, 190, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 'Flame Pokémon', 'When it swings its burning tail, it elevates the temperature to unbearably high levels.'),
  (6, 'charizard', 17, 905, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 'Flame Pokémon', 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.'),
  (7, 'squirtle', 5, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', 'Tiny Turtle Pokémon', 'After birth, its back swells and hardens into a shell. It powerfully sprays foam from its mouth.'),
  (8, 'wartortle', 10, 225, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 'Turtle Pokémon', 'It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.'),
  (9, 'blastoise', 16, 855, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 'Shellfish Pokémon', 'It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.'),
  (25, 'pikachu', 4, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'Mouse Pokémon', 'When several of these Pokémon gather, their electricity could build and cause lightning storms.');

insert into pokemon_ability (pokemon_id, position, name) values
  (1, 0, 'overgrow'),
  (1, 1, 'chlorophyll'),
  (2, 0, 'overgrow'),
  (2, 1, 'chlorophyll'),
  (3, 0, 'overgrow'),
  (3, 1, 'chlorophyll'),
  (4, 0, 'blaze'),
  (4, 1, 'solar-power'),
  (5, 0, 'blaze'),
  (5, 1, 'solar-power'),
  (6, 0, 'blaze'),
  (6, 1, 'solar-power'),
  (7, 0, 'torrent'),
  (7, 1, 'rain-dish'),
  (8, 0, 'torrent'),
  (8, 1, 'rain-dish'),
  (9, 0, 'torrent'),
  (9, 1, 'rain-dish'),
  (25, 0, 'static'),
  (25, 1, 'lightning-rod');

insert into pokemon_stat (pokemon_id, position, name, base_stat) values
  (1, 0, 'hp', 45),
  (1, 1, 'attack', 49),
  (1, 2, 'defense', 49),
  (1, 3, 'special-attack', 65),
  (1, 4, 'special-defense', 65),
  (1, 5, 'speed', 45),
  (2, 0, 'hp', 60),
  (2, 1, 'attack', 62),
  (2, 2, 'defense', 63),
  (2, 3, 'special-attack', 80),
  (2, 4, 'special-defense', 80),
  (2, 5, 'speed', 60),
  (3, 0, 'hp', 80),
  (3, 1, 'attack', 82),
  (3, 2, 'defense', 83),
  (3, 3, 'special-attack', 100),
  (3, 4, 'special-defense', 100),
  (3, 5, 'speed', 80),
  (4, 0, 'hp', 39),
  (4, 1, 'attack', 52),
  (4, 2, 'defense', 43),
  (4, 3, 'special-attack', 60),
  (4, 4, 'special-defense', 50),
  (4, 5, 'speed', 65),
  (5, 0, 'hp', 58),
  (5, 1, 'attack', 64),
  (5, 2, 'defense', 58),
  (5, 3, 'special-attack', 80),
  (5, 4, 'special-defense', 65),
  (5, 5, 'speed', 80),
  (6, 0, 'hp', 78),
  (6, 1, 'attack', 84),
  (6, 2, 'defense', 78),
  (6, 3, 'special-attack', 109),
  (6, 4, 'special-defense', 85),
  (6, 5, 'speed', 100),
  (7, 0, 'hp', 44),
  (7, 1, 'attack', 48),
  (7, 2, 'defense', 65),
  (7, 3, 'special-attack', 50),
  (7, 4, 'special-defense', 64),
  (7, 5, 'speed', 43),
  (8, 0, 'hp', 59),
  (8, 1, 'attack', 63),
  (8, 2, 'defense', 80),
  (8, 3, 'special-attack', 65),
  (8, 4, 'special-defense', 80),
  (8, 5, 'speed', 58),
  (9, 0, 'hp', 79),
  (9, 1, 'attack', 83),
  (9, 2, 'defense', 100),
  (9, 3, 'special-attack', 85),
  (9, 4, 'special-defense', 105),
  (9, 5, 'speed', 78),
  (25, 0, 'hp', 35),
  (25, 1, 'attack', 55),
  (25, 2, 'defense', 40),
  (25, 3, 'special-attack', 50),
  (25, 4, 'special-defense', 50),
  (25, 5, 'speed', 90);

insert into pokemon_evolution (pokemon_id, position, evolution_id, name, sprite_url, stage, evolves_from) values
  (1, 0, 1, 'bulbasaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 0, null),
  (1, 1, 2, 'ivysaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 1, 'bulbasaur'),
  (1, 2, 3, 'venusaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 2, 'ivysaur'),
  (2, 0, 1, 'bulbasaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 0, null),
  (2, 1, 2, 'ivysaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 1, 'bulbasaur'),
  (2, 2, 3, 'venusaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 2, 'ivysaur'),
  (3, 0, 1, 'bulbasaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 0, null),
  (3, 1, 2, 'ivysaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 1, 'bulbasaur'),
  (3, 2, 3, 'venusaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 2, 'ivysaur'),
  (4, 0, 4, 'charmander', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 0, null),
  (4, 1, 5, 'charmeleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 1, 'charmander'),
  (4, 2, 6, 'charizard', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 2, 'charmeleon'),
  (5, 0, 4, 'charmander', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 0, null),
  (5, 1, 5, 'charmeleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 1, 'charmander'),
  (5, 2, 6, 'charizard', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 2, 'charmeleon'),
  (6, 0, 4, 'charmander', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 0, null),
  (6, 1, 5, 'charmeleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 1, 'charmander'),
  (6, 2, 6, 'charizard', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 2, 'charmeleon'),
  (7, 0, 7, 'squirtle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', 0, null),
  (7, 1, 8, 'wartortle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 1, 'squirtle'),
  (7, 2, 9, 'blastoise', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 2, 'wartortle'),
  (8, 0, 7, 'squirtle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', 0, null),
  (8, 1, 8, 'wartortle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 1, 'squirtle'),
  (8, 2, 9, 'blastoise', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 2, 'wartortle'),
  (9, 0, 7, 'squirtle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', 0, null),
  (9, 1, 8, 'wartortle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 1, 'squirtle'),
  (9, 2, 9, 'blastoise', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 2, 'wartortle'),
  (25, 0, 25, 'pikachu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 0, null);
